export const latamCountries = [
  "Argentina",
  "Bolivia",
  "Brasil",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Ecuador",
  "El Salvador",
  "Guatemala",
  "Haití",
  "Honduras",
  "México",
  "Nicaragua",
  "Panamá",
  "Paraguay",
  "Perú",
  "República Dominicana",
  "Uruguay",
  "Venezuela",
];

export const sports = [
  "Fútbol",
  "Baloncesto",
  "Tenis",
  "Voleibol",
  "Balonmano",
  "Béisbol",
  "Cricket",
  "Rugby",
  "Fútbol americano",
  "Hockey sobre hielo",
  "Hockey sobre césped",
  "Atletismo",
  "Natación",
  "Ciclismo",
  "Boxeo",
  "Artes marciales mixtas (MMA)",
  "Judo",
  "Karate",
  "Taekwondo",
  "Gimnasia",
  "Patinaje artístico",
  "Esquí",
  "Snowboard",
  "Surf",
  "Windsurf",
  "Skateboarding",
  "Golf",
  "Tenis de mesa",
  "Bádminton",
  "Squash",
  "Polo",
  "Equitación",
  "Vela",
  "Remo",
  "Piragüismo",
  "Triatlón",
  "Pentatlón moderno",
  "Esgrima",
  "Tiro con arco",
  "Tiro olímpico",
  "Halterofilia",
  "Lanzamiento de jabalina",
  "Lanzamiento de disco",
  "Lanzamiento de martillo",
  "Salto de longitud",
  "Salto de altura",
  "Salto con pértiga",
  "Maratón",
  "Marcha atlética",
  "Waterpolo",
  "Curling",
];
